image: python:3.6

pages:
  stage: build
  script:
    - pip install --no-cache-dir -r dependencies.txt
    - python -c "from app import app; from flask_frozen import Freezer; Freezer(app).freeze()"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always